### ISSUE TITLE
How add killswitch to startup and allow system connect only to VPN servers.

### ISSUE THREAD

**Issue by hyrris** [vpn-kill-switch/killswitch#16]
Subject, Thanks.

**Comment by nbari** [comment]
Hi @hyrris , if need something at startup, is better to add permanent your [rules](https://vpn-kill-switch.com/post/pf/) in `/etc/pf.conf` for example and let the operating system load them automatically on boot time.

For this to work you need to know in advance the peer IP or your VPN endpoints otherwise, you will be locked since you won't be available to connect to your VPN provider.

**Comment by hyrris** [comment]
Hi @nbari, 
Thanks for reply.
I know all ip of my VPN servers.
So how lock any connection of system to internet(local - ok) not thru VPN  ?

**Comment by nbari** [comment]
If you know your endpoints you could do better by just implementing your own set of rules, no need to use `killswitch` to find them.
